flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- ConfigFile-1.1.4
- HUnit-1.3.1.1
- MissingH-1.4.0.1
- StateVar-1.1.0.4
- blaze-builder-0.4.0.2
- brick-0.8
- contravariant-1.4
- data-default-0.7.1.1
- data-default-class-0.1.2.0
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- dlist-0.7.1.2
- hashable-1.2.4.0
- hslogger-1.2.10
- microlens-0.4.5.0
- microlens-mtl-0.1.9.0
- microlens-th-0.4.0.0
- mtl-2.2.1
- network-2.6.2.1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parallel-3.2.1.0
- parsec-3.1.11
- primitive-0.6.1.0
- random-1.1
- regex-base-0.93.2
- regex-compat-0.95.1
- regex-posix-0.95.2
- semigroups-0.18.2
- stm-2.4.4.1
- text-1.2.2.1
- text-zipper-0.4
- transformers-compat-0.5.1.4
- utf8-string-1.0.1.1
- vector-0.11.0.0
- void-0.7.1
- vty-5.7.1
resolver: ghc-8.0.1
